name = "bth-hermit"
license = "MIT"
description = "rolotony browntown"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "featured image",
  "theme toggle",
]

[author]
  name = "brtholomy"
